In [2]:
# import dependencies
import requests
import pandas as pd

In [2]:
#list for API calls
key = '6924a24c5e8fd68ab4c75b8911dde245'
state_ids = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL',
             'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA',
             'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE',
             'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK',
             'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT',
             'VA', 'WA', 'WI', 'WV', 'WY']

In [3]:
#create dataframe and read in the json file holding personal income per capita using FRED api.
for x in state_ids:
  RINCPC = f"https://api.stlouisfed.org/fred/series/observations?series_id={x}RPIPC&api_key={key}&file_type=json"
  response = requests.get(RINCPC)
  series = pd.DataFrame(response.json()["observations"])
  series["value"] = series.rename(columns={'value': x}, inplace=True)
  series = series[['date', x]]
  if x == state_ids[0]:
    df = series
  else:
    df = pd.merge(df, series, on='date', how='inner')

In [ ]:
#Transpose data for compatibility with other SQL tables.
df = df.set_index('date').T
df = df.rename(columns={'2008-01-01': '2008', '2009-01-01': '2009', '2010-01-01': '2010', '2011-01-01': '2011',
                        '2012-01-01': '2012', '2013-01-01': '2013', '2014-01-01': '2014', '2015-01-01': '2015',
                        '2016-01-01': '2016', '2017-01-01': '2017', '2018-01-01': '2018', '2019-01-01': '2019',
                        '2020-01-01': '2020', '2021-01-01': '2021', '2022-01-01': '2022'})
df = df.rename(index={'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
                      'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida', 'GA': 'Georgia',
                      'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas',
                      'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts',
                      'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana',
                      'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico',
                      'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma',
                      'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina', 'SD': 'South Dakota',
                      'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington',
                      'WI': 'Wisconsin', 'WV': 'West Virginia', 'WY': 'Wyoming'})
df = df.reset_index()
df = df.rename(columns={'index': 'Region/state of residence'})

In [4]:
#print dataframe to csv - real income - has income per capita income per state
df.to_csv('realincome.csv', encoding='utf-8', index=False)

In [5]:
income_csv = pd.read_csv('realincome.csv')
income_csv

,date,AL,AK,AZ,AR,CA,CO,CT,DE,FL,...,SD,TN,TX,UT,VT,VA,WA,WI,WV,WY
0,2008-01-01,42242,51624,38967,40983,43801,46677,61514,45923,43264,...,53966,42800,46111,39101,45363,49384,47357,46757,40351,58234
1,2009-01-01,41995,50046,36641,40970,42404,44290,60539,45268,41222,...,51592,42858,43378,35790,44683,48503,44859,45576,41150,51850
2,2010-01-01,41757,53121,37162,40280,43519,44902,63476,44779,42760,...,51386,42936,44111,36432,46082,48535,45638,45543,40655,53752
3,2011-01-01,41849,54738,38384,41286,44858,45642,62986,47058,43276,...,55027,43816,46689,36776,47570,49648,46298,47258,41704,55954
4,2012-01-01,41617,55069,39253,43016,46170,46712,62599,46587,43193,...,52730,44341,47581,37963,47494,50704,48625,47869,41807,58962
5,2013-01-01,41356,53511,39171,42407,45839,47730,60177,46599,42278,...,52096,43980,47335,38301,47120,48674,48421,47518,40670,56738
6,2014-01-01,42010,55466,40235,44095,47491,50254,62124,46908,43817,...,53856,44719,48987,39622,49298,49591,49895,48519,41592,59527
7,2015-01-01,43835,56504,41903,45429,50074,51326,63350,49657,45696,...,56578,46540,49009,42061,49460,51300,51713,50674,42149,59581
8,2016-01-01,43577,54409,42530,45891,51845,50932,64059,49888,46131,...,56333,46690,47705,43390,50635,52229,52455,50962,42098,55726
9,2017-01-01,44472,54005,44250,46835,52604,52739,64665,50850,48133,...,56740,47828,49944,43710,49930,53826,52990,51771,43731,58146
10,2018-01-01,46441,55410,45656,48479,53481,56587,68093,52109,49932,...,55499,50874,51578,46524,50638,54030,54841,52805,45021,62945
11,2019-01-01,47123,56881,47219,48268,55915,57850,69110,52615,52072,...,57344,51841,52351,47932,52739,56432,56828,53670,46591,63624
12,2020-01-01,50207,58532,50355,51209,60011,59863,70544,55233,53888,...,62351,54946,53456,52063,54402,58311,60169,57334,49453,68414
13,2021-01-01,52290,57623,53694,53390,63271,64282,72206,55553,57193,...,66784,57819,56565,55448,57077,60057,62680,59557,49594,70876
14,2022-01-01,50053,58069,50480,52430,59103,63875,67254,55709,54746,...,66857,54794,55382,54307,53806,58281,59175,57465,48337,68772

In [3]:
df2 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 11 Personal Health Care')
df3 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 12 Hospital')
df4 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 13 Physician and Clinics')
df5 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 14 Other Professionals')
df7 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 16 Home Health')
df8 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 17 Nursing')
df14 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 29 Private Per Enrollee')

name2 = 'Personal Health Care'
name3 = 'Hospital'
name4 = 'Physician and Clinics'
name5 = 'Other Professionals'
name7 = 'Home Health'
name8 = 'Nursing'
name14 = 'Private Per Enrollee'

In [5]:
def clean(data):
    dat = data
    dat.columns = (dat.iloc[0])
    dat = dat.drop(62)
    dat = dat.drop(61)
    dat = dat.drop(0)
    dat = dat.rename(columns= {2008.0: 2008, 2009.0: 2009, 2010.0: 2010, 2011.0: 2011, 2012.0: 2012, 2013.0: 2013, 2014.0: 2014,
                           2015.0: 2015, 2016.0: 2016, 2017.0: 2017, 2018.0: 2018, 2019.0: 2019, 2020.0: 2020})
    dat = dat[['Region/state of residence', 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]]
    dat = dat.astype({2008: int, 2009: int, 2010: int, 2011: int, 2012: int, 2013: int, 2014: int,
                           2015: int, 2016: int, 2017: int, 2018: int, 2019: int, 2020: int})    
    # dat = pd.DataFrame(dat).set_index('Region/state of residence')
    if data.equals(df2):
        dat.to_csv(f'Data\{name2}.csv', encoding='utf-8', index=False)
    elif data.equals(df3):
        dat.to_csv(f'Data\{name3}.csv', encoding='utf-8', index=False)
    elif data.equals(df4):
        dat.to_csv(f'Data\{name4}.csv', encoding='utf-8', index=False)
    elif data.equals(df5):
        dat.to_csv(f'Data\{name5}.csv', encoding='utf-8', index=False)
    elif data.equals(df7):
        dat.to_csv(f'Data\{name7}.csv', encoding='utf-8', index=False)
    elif data.equals(df8):
        dat.to_csv(f'Data\{name8}.csv', encoding='utf-8', index=False)
    elif data.equals(df14):
        dat.to_csv(f'Data\{name14}.csv', encoding='utf-8', index=False)
    return dat

In [6]:
clean(df2), clean(df3), clean(df4), clean(df5), clean(df7), clean(df8), clean(df14)

(0  Region/state of residence   2008    2009    2010    2011    2012    2013  \
 1              United States  371.0   397.0   414.0   422.0   442.0   457.0
 2                New England  668.0   749.0   752.0   731.0   774.0   788.0
 3                Connecticut  636.0   834.0   809.0   679.0   776.0   792.0
 4                      Maine  958.0  1001.0   957.0   953.0   928.0   934.0
 5              Massachusetts  621.0   665.0   686.0   707.0   736.0   741.0
 6              New Hampshire  421.0   455.0   479.0   509.0   567.0   618.0
 7               Rhode Island  852.0   843.0   803.0   784.0   769.0   748.0
 8                    Vermont  930.0  1062.0  1166.0  1184.0  1282.0  1384.0
 9                    Mideast  589.0   636.0   682.0   710.0   702.0   701.0
 10                  Delaware  391.0   410.0   424.0   460.0   473.0   476.0
 11      District of Columbia  447.0   532.0  1003.0  1028.0   947.0   934.0
 12                  Maryland  348.0   385.0   427.0   428.0   451.0   475.0
 13                New Jersey  387.0   407.0   431.0   466.0   464.0   448.0
 14                  New York  774.0   843.0   883.0   912.0   882.0   873.0
 15              Pennsylvania  576.0   614.0   667.0   703.0   713.0   722.0
 16               Great Lakes  333.0   353.0   372.0   379.0   396.0   412.0
 17                  Illinois  348.0   364.0   401.0   399.0   420.0   448.0
 18                   Indiana  321.0   342.0   349.0   349.0   352.0   367.0
 19                  Michigan  254.0   266.0   286.0   305.0   334.0   341.0
 20                      Ohio  382.0   415.0   449.0   446.0   462.0   474.0
 21                 Wisconsin  355.0   364.0   328.0   360.0   366.0   377.0
 22                    Plains  458.0   486.0   503.0   515.0   538.0   571.0
 23                      Iowa  447.0   487.0   519.0   530.0   551.0   584.0
 24                    Kansas  404.0   434.0   421.0   435.0   438.0   438.0
 25                 Minnesota  707.0   728.0   756.0   768.0   796.0   842.0
 26                  Missouri  307.0   329.0   335.0   353.0   380.0   423.0
 27                  Nebraska  341.0   376.0   397.0   378.0   402.0   425.0
 28              North Dakota  523.0   572.0   654.0   699.0   723.0   763.0
 29              South Dakota  387.0   410.0   429.0   441.0   465.0   470.0
 30                 Southeast  289.0   308.0   318.0   320.0   330.0   331.0
 31                   Alabama  282.0   284.0   296.0   320.0   310.0   316.0
 32                  Arkansas  307.0   348.0   425.0   447.0   469.0   491.0
 33                   Florida  235.0   241.0   252.0   232.0   241.0   251.0
 34                   Georgia  185.0   193.0   195.0   205.0   237.0   258.0
 35                  Kentucky  310.0   344.0   387.0   384.0   395.0   406.0
 36                 Louisiana  419.0   438.0   481.0   477.0   494.0   486.0
 37               Mississippi  281.0   309.0   340.0   356.0   369.0   366.0
 38            North Carolina  374.0   405.0   361.0   348.0   321.0   259.0
 39            South Carolina  282.0   278.0   286.0   284.0   292.0   282.0
 40                 Tennessee  329.0   359.0   352.0   363.0   384.0   407.0
 41                  Virginia  293.0   331.0   351.0   379.0   386.0   402.0
 42             West Virginia  450.0   500.0   542.0   588.0   658.0   654.0
 43                 Southwest  286.0   300.0   309.0   299.0   294.0   308.0
 44                   Arizona  331.0   363.0   382.0   318.0   308.0   316.0
 45                New Mexico  465.0   450.0   459.0   421.0   421.0   437.0
 46                  Oklahoma  357.0   375.0   365.0   371.0   376.0   387.0
 47                     Texas  249.0   260.0   270.0   274.0   268.0   284.0
 48           Rocky Mountains  307.0   325.0   336.0   330.0   353.0   361.0
 49                  Colorado  293.0   314.0   311.0   321.0   338.0   336.0
 50                     Idaho  299.0   318.0   400.0   287.0   327.0   352.0
 51                   Montana  359.0   379.0   418.0   431.0   472.0   493.0
 52                      Utah  292.0   303.0   293.0   308.0   328.0   341.0
 53                   Wyoming  432.0   450.0   441.0   467.0   468.0   473.0
 54                  Far West  280.0   302.0   314.0   333.0   413.0   459.0
 55                    Alaska  542.0   576.0   634.0   698.0   805.0   866.0
 56                California  262.0   280.0   290.0   314.0   420.0   468.0
 57                    Hawaii  265.0   221.0   204.0   199.0   200.0   205.0
 58                    Nevada  152.0   171.0   200.0   211.0   219.0   227.0
 59                    Oregon  476.0   551.0   578.0   601.0   592.0   670.0
 60                Washington  295.0   319.0   332.0   326.0   354.0   388.0

 0     2014    2015    2016    2017    2018    2019    2020
 1    478.0   515.0   542.0   569.0   584.0   596.0   634.0
 2    832.0   916.0   953.0   968.0  1049.0  1073.0  1125.0
 3    842.0   955.0  1006.0  1048.0  1075.0  1083.0  1092.0
 4   1024.0  1039.0  1083.0  1127.0  1231.0  1370.0  1438.0
 5    786.0   897.0   950.0   949.0  1086.0  1094.0  1163.0
 6    609.0   638.0   690.0   742.0   744.0   761.0   810.0
 7    745.0   735.0   654.0   656.0   669.0   738.0   803.0
 8   1475.0  1529.0  1487.0  1385.0  1394.0  1386.0  1449.0
 9    742.0   807.0   873.0   963.0  1018.0  1016.0  1058.0
 10   482.0   484.0   501.0   567.0   549.0   577.0   625.0
 11  1029.0  1040.0  1067.0  1129.0  1149.0  1197.0  1344.0
 12   499.0   546.0   566.0   605.0   629.0   657.0   730.0
 13   528.0   510.0   546.0   557.0   595.0   640.0   661.0
 14   893.0  1011.0  1111.0  1249.0  1303.0  1311.0  1438.0
 15   775.0   832.0   895.0   998.0  1088.0  1020.0   933.0
 16   428.0   464.0   468.0   478.0   489.0   495.0   532.0
 17   444.0   473.0   455.0   449.0   475.0   471.0   512.0
 18   394.0   424.0   415.0   444.0   474.0   487.0   519.0
 19   326.0   343.0   349.0   350.0   343.0   359.0   399.0
 20   540.0   611.0   647.0   668.0   660.0   659.0   698.0
 21   384.0   399.0   398.0   422.0   443.0   455.0   486.0
 22   590.0   608.0   626.0   645.0   660.0   683.0   713.0
 23   615.0   646.0   540.0   456.0   500.0   496.0   500.0
 24   381.0   373.0   379.0   376.0   378.0   403.0   418.0
 25   915.0   925.0   992.0  1095.0  1110.0  1142.0  1225.0
 26   416.0   437.0   472.0   490.0   484.0   518.0   519.0
 27   439.0   478.0   503.0   470.0   538.0   551.0   584.0
 28   847.0   879.0   949.0   971.0   956.0   939.0   981.0
 29   484.0   506.0   508.0   532.0   545.0   561.0   572.0
 30   347.0   354.0   362.0   376.0   376.0   382.0   386.0
 31   329.0   337.0   345.0   348.0   348.0   351.0   354.0
 32   553.0   552.0   576.0   584.0   562.0   465.0   429.0
 33   255.0   260.0   275.0   293.0   283.0   284.0   295.0
 34   267.0   275.0   283.0   299.0   310.0   324.0   331.0
 35   469.0   480.0   479.0   483.0   494.0   547.0   534.0
 36   487.0   484.0   492.0   517.0   519.0   568.0   589.0
 37   407.0   404.0   414.0   427.0   431.0   442.0   448.0
 38   274.0   272.0   270.0   285.0   276.0   285.0   300.0
 39   310.0   321.0   340.0   337.0   355.0   365.0   358.0
 40   420.0   440.0   431.0   449.0   472.0   480.0   465.0
 41   419.0   446.0   469.0   493.0   486.0   480.0   491.0
 42   670.0   653.0   606.0   602.0   600.0   640.0   637.0
 43   333.0   376.0   398.0   405.0   403.0   404.0   418.0
 44   367.0   411.0   438.0   470.0   457.0   486.0   526.0
 45   454.0   499.0   532.0   558.0   563.0   595.0   621.0
 46   380.0   390.0   394.0   397.0   387.0   419.0   406.0
 47   309.0   356.0   379.0   378.0   380.0   367.0   378.0
 48   373.0   404.0   425.0   438.0   463.0   484.0   485.0
 49   335.0   358.0   384.0   390.0   417.0   437.0   422.0
 50   382.0   416.0   420.0   443.0   452.0   463.0   465.0
 51   550.0   617.0   622.0   655.0   633.0   659.0   649.0
 52   354.0   392.0   415.0   425.0   472.0   496.0   530.0
 53   476.0   492.0   523.0   572.0   592.0   618.0   630.0
 54   471.0   521.0   571.0   605.0   610.0   649.0   763.0
 55   889.0   950.0  1021.0  1127.0  1156.0  1258.0  1255.0
 56   472.0   527.0   577.0   613.0   603.0   640.0   790.0
 57   209.0   220.0   224.0   225.0   244.0   267.0   263.0
 58   258.0   282.0   298.0   329.0   331.0   363.0   339.0
 59   784.0   809.0   842.0   865.0   895.0   948.0  1002.0
 60   383.0   439.0   512.0   554.0   616.0   656.0   714.0  ,
 0  Region/state of residence     2008     2009     2010     2011     2012  \
 1              United States   9959.0  10339.0  10493.0  10721.0  10741.0
 2                New England  10048.0  10439.0  10558.0  10779.0  10799.0
 3                Connecticut  10702.0  11060.0  11080.0  11343.0  11263.0
 4                      Maine   8293.0   8647.0   8622.0   8952.0   8872.0
 5              Massachusetts  10742.0  11200.0  11384.0  11566.0  11684.0
 6              New Hampshire   8355.0   8597.0   8698.0   9122.0   9084.0
 7               Rhode Island   9662.0  10103.0  10320.0  10332.0  10305.0
 8                    Vermont   8183.0   8479.0   8750.0   8837.0   8943.0
 9                    Mideast  10913.0  11271.0  11403.0  11692.0  11625.0
 10                  Delaware  10157.0  10358.0  10589.0  10930.0  10836.0
 11      District of Columbia  11031.0  11210.0  11312.0  11549.0  11549.0
 12                  Maryland  11178.0  11334.0  11407.0  11904.0  11727.0
 13                New Jersey  11504.0  11848.0  12028.0  12302.0  12172.0
 14                  New York  11169.0  11587.0  11695.0  11958.0  11954.0
 15              Pennsylvania  10194.0  10563.0  10712.0  10966.0  10893.0
 16               Great Lakes   9847.0  10234.0  10384.0  10629.0  10614.0
 17                  Illinois  10173.0  10550.0  10764.0  11026.0  10960.0
 18                   Indiana   9352.0   9790.0  10003.0  10323.0  10354.0
 19                  Michigan  10514.0  10862.0  10889.0  11048.0  11048.0
 20                      Ohio   9849.0  10286.0  10490.0  10775.0  10721.0
 21                 Wisconsin   8518.0   8837.0   8898.0   9106.0   9200.0
 22                    Plains   8741.0   9017.0   9206.0   9433.0   9553.0
 23                      Iowa   8036.0   8301.0   8485.0   8762.0   8914.0
 24                    Kansas   9084.0   9312.0   9554.0   9759.0   9780.0
 25                 Minnesota   8648.0   8859.0   9005.0   9176.0   9294.0
 26                  Missouri   9290.0   9666.0   9829.0  10011.0  10153.0
 27                  Nebraska   8731.0   9016.0   9332.0   9518.0   9595.0
 28              North Dakota   7686.0   7740.0   7965.0   8608.0   8900.0
 29              South Dakota   7730.0   7971.0   8151.0   8645.0   8736.0
 30                 Southeast   9932.0  10333.0  10495.0  10695.0  10719.0
 31                   Alabama   9473.0   9710.0   9821.0   9942.0  10006.0
 32                  Arkansas   8635.0   8877.0   8939.0   9162.0   9240.0
 33                   Florida  11354.0  11958.0  12057.0  12293.0  12325.0
 34                   Georgia   9450.0   9811.0  10016.0  10162.0  10247.0
 35                  Kentucky   9256.0   9561.0   9823.0  10098.0  10104.0
 36                 Louisiana  11329.0  11734.0  12016.0  12145.0  11963.0
 37               Mississippi  10245.0  10621.0  10873.0  10932.0  10928.0
 38            North Carolina   9345.0   9706.0   9914.0  10124.0  10120.0
 39            South Carolina   9285.0   9605.0   9837.0   9986.0  10026.0
 40                 Tennessee   9625.0  10019.0  10130.0  10250.0  10224.0
 41                  Virginia   8436.0   8733.0   8890.0   9200.0   9287.0
 42             West Virginia   9012.0   9253.0   9422.0   9716.0   9796.0
 43                 Southwest  10267.0  10681.0  10872.0  11047.0  11030.0
 44                   Arizona   9054.0   9417.0   9611.0   9921.0   9970.0
 45                New Mexico   7811.0   8131.0   8273.0   8476.0   8545.0
 46                  Oklahoma   9688.0   9934.0  10238.0  10285.0  10192.0
 47                     Texas  11020.0  11492.0  11663.0  11814.0  11779.0
 48           Rocky Mountains   7960.0   8272.0   8432.0   8589.0   8697.0
 49                  Colorado   8376.0   8702.0   8865.0   8943.0   9023.0
 50                     Idaho   7455.0   7800.0   7877.0   8181.0   8351.0
 51                   Montana   7324.0   7421.0   7596.0   7683.0   7821.0
 52                      Utah   7947.0   8300.0   8425.0   8638.0   8730.0
 53                   Wyoming   7596.0   8001.0   8444.0   8717.0   8826.0
 54                  Far West   9792.0  10197.0  10338.0  10595.0  10701.0
 55                    Alaska   8089.0   8617.0   8554.0   8828.0   8783.0
 56                California  10549.0  10975.0  11142.0  11421.0  11529.0
 57                    Hawaii   7406.0   7686.0   7864.0   8143.0   8307.0
 58                    Nevada   9291.0   9756.0  10043.0  10342.0  10389.0
 59                    Oregon   7909.0   8220.0   8316.0   8504.0   8567.0
 60                Washington   8054.0   8437.0   8448.0   8631.0   8803.0

 0      2013     2014     2015     2016     2017     2018     2019     2020
 1   10796.0  10965.0  11168.0  11279.0  11529.0  11871.0  12372.0  12271.0
 2   10884.0  11167.0  11398.0  11521.0  11699.0  11991.0  12419.0  12011.0
 3   11592.0  11898.0  12113.0  12173.0  12472.0  12635.0  13136.0  12905.0
 4    9013.0   9287.0   9493.0   9700.0  10019.0  10255.0  10732.0  10343.0
 5   11600.0  11927.0  12199.0  12314.0  12425.0  12902.0  13391.0  12917.0
 6    9214.0   9304.0   9561.0   9844.0  10092.0  10493.0  10752.0  10086.0
 7   10519.0  10861.0  10894.0  10913.0  10856.0  11009.0  11420.0  11231.0
 8    9047.0   9195.0   9497.0   9662.0   9829.0   9234.0   9088.0   8726.0
 9   11694.0  11910.0  12100.0  12177.0  12377.0  12691.0  13138.0  12876.0
 10  11126.0  11525.0  11632.0  11790.0  11867.0  12184.0  12594.0  12101.0
 11  11714.0  11840.0  12266.0  12470.0  12662.0  12844.0  13296.0  13350.0
 12  11824.0  12058.0  12319.0  12331.0  12625.0  12820.0  13206.0  12805.0
 13  12303.0  12625.0  12756.0  12931.0  12957.0  13308.0  13589.0  13084.0
 14  11952.0  12110.0  12288.0  12381.0  12578.0  12923.0  13552.0  13379.0
 15  10987.0  11203.0  11412.0  11422.0  11706.0  12004.0  12331.0  12160.0
 16  10704.0  10869.0  10972.0  11076.0  11339.0  11646.0  12087.0  11886.0
 17  10967.0  11129.0  11231.0  11373.0  11603.0  11982.0  12409.0  12109.0
 18  10517.0  10706.0  10834.0  11014.0  11269.0  11621.0  12131.0  12126.0
 19  11109.0  11251.0  11380.0  11392.0  11592.0  11726.0  12102.0  11773.0
 20  10878.0  11000.0  11021.0  11132.0  11460.0  11801.0  12286.0  12148.0
 21   9286.0   9571.0   9775.0   9881.0  10204.0  10571.0  11002.0  10886.0
 22   9680.0   9946.0  10174.0  10269.0  10664.0  11018.0  11363.0  11291.0
 23   9079.0   9240.0   9506.0   9587.0   9974.0  10283.0  10741.0  10684.0
 24   9831.0  10105.0  10223.0  10289.0  10640.0  11065.0  11469.0  11347.0
 25   9508.0   9880.0  10206.0  10236.0  10773.0  11147.0  11131.0  10899.0
 26  10204.0  10446.0  10582.0  10715.0  11052.0  11390.0  11935.0  11985.0
 27   9737.0   9897.0  10228.0  10301.0  10657.0  11083.0  11496.0  11541.0
 28   9082.0   9451.0   9698.0   9971.0  10342.0  10572.0  10855.0  10843.0
 29   8925.0   9268.0   9573.0   9818.0  10064.0  10342.0  10736.0  10567.0
 30  10717.0  10837.0  11031.0  11128.0  11392.0  11760.0  12344.0  12334.0
 31  10061.0  10247.0  10489.0  10612.0  10919.0  11343.0  11945.0  12013.0
 32   9253.0   9435.0   9689.0   9898.0  10268.0  10728.0  11299.0  11284.0
 33  12186.0  12263.0  12484.0  12393.0  12518.0  12913.0  13570.0  13652.0
 34  10315.0  10394.0  10562.0  10812.0  11139.0  11543.0  12192.0  12256.0
 35  10211.0  10306.0  10388.0  10628.0  11054.0  11337.0  11818.0  11658.0
 36  11786.0  11801.0  11954.0  12064.0  12277.0  12613.0  13059.0  13177.0
 37  10823.0  10986.0  11214.0  11380.0  11703.0  12075.0  12682.0  12426.0
 38  10210.0  10291.0  10481.0  10603.0  10839.0  11263.0  11812.0  11810.0
 39  10114.0  10278.0  10397.0  10510.0  10862.0  11229.0  11820.0  11884.0
 40  10144.0  10334.0  10579.0  10722.0  11113.0  11312.0  11877.0  11894.0
 41   9453.0   9615.0   9764.0   9906.0  10162.0  10482.0  10947.0  10622.0
 42   9972.0  10233.0  10366.0  10652.0  10980.0  11335.0  11853.0  11522.0
 43  11025.0  11188.0  11388.0  11492.0  11762.0  12146.0  12711.0  12716.0
 44  10033.0  10100.0  10279.0  10400.0  10845.0  11213.0  11495.0  11477.0
 45   8581.0   8709.0   8873.0   9087.0   9302.0   9579.0   9953.0   9796.0
 46  10185.0  10460.0  10717.0  10964.0  11435.0  11921.0  12629.0  12428.0
 47  11745.0  11919.0  12118.0  12178.0  12362.0  12744.0  13394.0  13458.0
 48   8709.0   8991.0   9179.0   9315.0   9693.0   9992.0  10412.0  10330.0
 49   8931.0   9239.0   9427.0   9549.0   9943.0  10234.0  10615.0  10582.0
 50   8410.0   8749.0   8886.0   9046.0   9230.0   9505.0   9928.0   9948.0
 51   8012.0   8208.0   8381.0   8600.0   9101.0   9275.0   9787.0   9338.0
 52   8824.0   9055.0   9221.0   9311.0   9802.0  10160.0  10665.0  10664.0
 53   8839.0   9096.0   9545.0   9712.0   9870.0  10342.0  10590.0  10274.0
 54  10828.0  10948.0  11272.0  11457.0  11648.0  12000.0  12532.0  12536.0
 55   9091.0   9357.0   9376.0   9888.0  10117.0  10524.0  11027.0  10600.0
 56  11680.0  11769.0  12146.0  12320.0  12488.0  12877.0  13485.0  13564.0
 57   8277.0   8547.0   8802.0   9006.0   9071.0   9342.0   9812.0   9837.0
 58  10553.0  10791.0  11118.0  11400.0  11662.0  12075.0  12614.0  12503.0
 59   8644.0   8904.0   9156.0   9372.0   9659.0   9940.0  10326.0  10263.0
 60   8875.0   8992.0   9172.0   9347.0   9606.0   9854.0  10164.0   9966.0  ,
 0  Region/state of residence     2008     2009     2010     2011     2012  \
 1              United States   6729.0   6803.0   6777.0   6646.0   6682.0
 2                New England  10292.0  10616.0   9888.0   9146.0   9183.0
 3                Connecticut   9936.0  10800.0   9156.0   8605.0   9344.0
 4                      Maine   7177.0   7936.0   6098.0   6742.0   7077.0
 5              Massachusetts  11804.0  11887.0  11941.0  10293.0   9697.0
 6              New Hampshire  10333.0  10250.0   9549.0   8111.0   8232.0
 7               Rhode Island  11074.0  10848.0  10660.0  10878.0  10697.0
 8                    Vermont   7788.0   7689.0   7532.0   7444.0   7994.0
 9                    Mideast   9844.0   9718.0   9491.0   9518.0   9158.0
 10                  Delaware   6659.0   6560.0   6291.0   6333.0   6876.0
 11      District of Columbia  10141.0  10694.0  10165.0   9937.0   9170.0
 12                  Maryland   8513.0   8434.0   8198.0   7797.0   7426.0
 13                New Jersey  10770.0  10617.0  10304.0  10068.0   9353.0
 14                  New York  10685.0  10561.0  10108.0  10275.0   9800.0
 15              Pennsylvania   8207.0   8052.0   8445.0   8502.0   8545.0
 16               Great Lakes   6070.0   6380.0   6214.0   5812.0   6029.0
 17                  Illinois   5302.0   5922.0   6157.0   4974.0   4937.0
 18                   Indiana   6948.0   6277.0   6024.0   5887.0   7602.0
 19                  Michigan   5711.0   5626.0   5549.0   5525.0   5852.0
 20                      Ohio   7161.0   7408.0   7190.0   7190.0   6747.0
 21                 Wisconsin   5675.0   7019.0   5926.0   5704.0   6134.0
 22                    Plains   8419.0   8515.0   8301.0   8079.0   8337.0
 23                      Iowa   7101.0   6837.0   6597.0   6686.0   6791.0
 24                    Kansas   7928.0   7972.0   7079.0   7370.0   6980.0
 25                 Minnesota   9859.0   9765.0   9747.0   8983.0   9088.0
 26                  Missouri   8260.0   8695.0   8442.0   8317.0   9015.0
 27                  Nebraska   8222.0   8174.0   8086.0   7721.0   8070.0
 28              North Dakota   9616.0   9685.0  10456.0  10561.0  11325.0
 29              South Dakota   6680.0   6908.0   7004.0   6484.0   6654.0
 30                 Southeast   5939.0   5922.0   6010.0   5806.0   5778.0
 31                   Alabama   5051.0   5136.0   5795.0   4802.0   5064.0