In [1]:
# import dependencies
import requests
import pandas as pd

In [2]:
#list for API calls
key = '6924a24c5e8fd68ab4c75b8911dde245'
state_ids = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL',
             'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA',
             'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE',
             'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK',
             'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT',
             'VA', 'WA', 'WI', 'WV', 'WY']

In [3]:
#create dataframe and read in the json file holding personal income per capita using FRED api.
for x in state_ids:
  RINCPC = f"https://api.stlouisfed.org/fred/series/observations?series_id={x}RPIPC&api_key={key}&file_type=json"
  response = requests.get(RINCPC)
  series = pd.DataFrame(response.json()["observations"])
  series["value"] = series.rename(columns={'value': x}, inplace=True)
  series = series[['date', x]]
  if x == state_ids[0]:
    df = series
  else:
    df = pd.merge(df, series, on='date', how='inner')

In [4]:
#Transpose data for compatibility with other SQL tables.
df = df.set_index('date').T
df = df.rename(columns={'2008-01-01': '2008', '2009-01-01': '2009', '2010-01-01': '2010', '2011-01-01': '2011',
                        '2012-01-01': '2012', '2013-01-01': '2013', '2014-01-01': '2014', '2015-01-01': '2015',
                        '2016-01-01': '2016', '2017-01-01': '2017', '2018-01-01': '2018', '2019-01-01': '2019',
                        '2020-01-01': '2020', '2021-01-01': '2021', '2022-01-01': '2022'})
df = df.rename(index={'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
                      'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida', 'GA': 'Georgia',
                      'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas',
                      'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts',
                      'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana',
                      'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico',
                      'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma',
                      'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina', 'SD': 'South Dakota',
                      'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington',
                      'WI': 'Wisconsin', 'WV': 'West Virginia', 'WY': 'Wyoming'})
df = df.reset_index()
df = df.rename(columns={'index': 'Region/state of residence'})

In [5]:
#print dataframe to csv - real income - has income per capita income per state
df.to_csv('Data/realincome.csv', encoding='utf-8', index=False)

In [8]:
income_csv = pd.read_csv('Data/realincome.csv')
income_csv

,Region/state of residence,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Alabama,42242,41995,41757,41849,41617,41356,42010,43835,43577,44472,46441,47123,50207,52290,50053
1,Alaska,51624,50046,53121,54738,55069,53511,55466,56504,54409,54005,55410,56881,58532,57623,58069
2,Arizona,38967,36641,37162,38384,39253,39171,40235,41903,42530,44250,45656,47219,50355,53694,50480
3,Arkansas,40983,40970,40280,41286,43016,42407,44095,45429,45891,46835,48479,48268,51209,53390,52430
4,California,43801,42404,43519,44858,46170,45839,47491,50074,51845,52604,53481,55915,60011,63271,59103
5,Colorado,46677,44290,44902,45642,46712,47730,50254,51326,50932,52739,56587,57850,59863,64282,63875
6,Connecticut,61514,60539,63476,62986,62599,60177,62124,63350,64059,64665,68093,69110,70544,72206,67254
7,Delaware,45923,45268,44779,47058,46587,46599,46908,49657,49888,50850,52109,52615,55233,55553,55709
8,Florida,43264,41222,42760,43276,43193,42278,43817,45696,46131,48133,49932,52072,53888,57193,54746
9,Georgia,42027,41967,40688,42371,41428,41342,42966,45162,45910,47164,48286,49770,52197,53954,50954
10,Hawaii,42839,41152,41970,42000,42548,40543,42368,43527,45057,45830,45669,46700,48300,50224,48095
11,Idaho,38633,37037,37925,38351,39456,39856,40851,42395,43501,43698,46334,48080,52322,54349,53199
12,Illinois,48415,45573,45785,46627,48180,48736,50192,52739,52593,53025,54882,56211,58848,61090,57654
13,Indiana,43045,41599,42305,43988,44694,44364,45290,47431,48119,49155,49297,50349,54014,56596,54811
14,Iowa,49431,46716,46319,49065,49603,49444,49950,52197,51997,52520,52149,52319,55518,59451,58769
15,Kansas,51282,48299,47376,49879,50983,51541,51212,51652,51703,52843,53374,54358,57114,58997,57958
16,Kentucky,41032,40970,40634,41304,41637,41149,42163,44004,44229,44983,45924,46924,50580,53132,50138
17,Louisiana,47048,45972,45712,45363,46373,46138,46963,47125,45906,47177,49184,49923,52801,54860,51925
18,Maine,42076,42256,43057,44300,43668,42448,45787,46058,46350,47144,47982,50609,53151,55479,51855
19,Maryland,50561,49375,50625,51131,51763,49966,50717,52493,53818,54699,55322,56828,58386,59801,57736
20,Massachusetts,54461,54176,55691,56417,57066,56794,57340,60375,59836,61749,63345,65445,68032,71971,66701
21,Michigan,41948,40151,40984,42716,43524,43132,44085,47214,48004,48940,48952,49322,53577,55251,52679
22,Minnesota,49860,46758,48225,50075,51557,50849,51753,54113,54497,55762,55425,56672,59982,62468,60785
23,Mississippi,39184,39758,39144,39422,40016,39978,40144,40954,41074,41757,42877,43791,47589,49677,45818
24,Missouri,47099,45186,43938,44788,45807,45178,45689,47602,48730,48939,49937,50619,54141,56045,54753
25,Montana,42420,41648,43077,43679,45708,45185,45340,46701,47043,48257,50187,50986,55822,58704,58297
26,Nebraska,50465,48959,49338,53822,53224,52247,54103,56086,54640,55273,54975,55874,58531,62680,61750
27,Nevada,42848,39476,40941,40739,41361,41179,42744,45719,46904,47169,50302,50824,53887,58810,55582
28,New Hampshire,48279,48280,49950,51172,52190,51260,52478,53641,53998,54856,57229,59512,61785,64766,59247
29,New Jersey,53849,50491,51790,52199,52513,52117,53254,55187,55877,56585,56760,58709,61418,64046,61250
30,New Mexico,39593,38605,39402,38977,39187,38133,39827,40734,41535,41045,43916,44966,48683,52357,49501
31,New York,48246,47526,48800,49369,50801,50345,51565,53135,54059,56703,57543,58669,60801,63666,60472
32,North Carolina,45877,44344,42730,42479,44045,42472,43823,45797,46302,47617,48656,50930,54314,55605,53226
33,North Dakota,53507,51491,54692,58846,64517,61532,63104,59820,57045,58576,59405,58763,63669,66621,68481
34,Ohio,44451,42857,43444,45541,45859,45670,46836,48871,49186,50277,50530,51273,55124,56903,54516
35,Oklahoma,49104,45641,45446,47134,48680,49838,51540,49911,46871,48368,50412,52205,53706,56420,54724
36,Oregon,42239,39641,40049,40590,40990,41192,43052,44953,46549,46979,47087,48631,52482,54976,50448
37,Pennsylvania,46902,45727,47012,48346,49316,49038,50322,51674,52720,52469,54503,55410,59170,61233,57849
38,Rhode Island,44835,43821,46190,46973,48020,46444,47874,48421,48637,49320,50153,52112,55605,57342,52380
39,South Carolina,40425,39578,39126,39851,40611,40249,41743,43675,44368,45728,46621,48799,51422,51875,49456
40,South Dakota,53966,51592,51386,55027,52730,52096,53856,56578,56333,56740,55499,57344,62351,66784,66857
41,Tennessee,42800,42858,42936,43816,44341,43980,44719,46540,46690,47828,50874,51841,54946,57819,54794
42,Texas,46111,43378,44111,46689,47581,47335,48987,49009,47705,49944,51578,52351,53456,56565,55382
43,Utah,39101,35790,36432,36776,37963,38301,39622,42061,43390,43710,46524,47932,52063,55448,54307
44,Vermont,45363,44683,46082,47570,47494,47120,49298,49460,50635,49930,50638,52739,54402,57077,53806
45,Virginia,49384,48503,48535,49648,50704,48674,49591,51300,52229,53826,54030,56432,58311,60057,58281
46,Washington,47357,44859,45638,46298,48625,48421,49895,51713,52455,52990,54841,56828,60169,62680,59175
47,Wisconsin,46757,45576,45543,47258,47869,47518,48519,50674,50962,51771,52805,53670,57334,59557,57465
48,West Virginia,40351,41150,40655,41704,41807,40670,41592,42149,42098,43731,45021,46591,49453,49594,48337
49,Wyoming,58234,51850,53752,55954,58962,56738,59527,59581,55726,58146,62945,63624,68414,70876,68772

In [ ]:
df2 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 11 Personal Health Care')
df3 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 12 Hospital')
df4 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 13 Physician and Clinics')
df5 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 14 Other Professionals')
df7 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 16 Home Health')
df8 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 17 Nursing')
df14 = pd.read_excel('Data\Residence_all_tables.xlsx', 'Table 29 Private Per Enrollee')

name2 = 'Personal Health Care'
name3 = 'Hospital'
name4 = 'Physician and Clinics'
name5 = 'Other Professionals'
name7 = 'Home Health'
name8 = 'Nursing'
name14 = 'Private Per Enrollee'

In [ ]:
def clean(data):
    dat = data
    dat.columns = (dat.iloc[0])
    dat = dat.drop(62)
    dat = dat.drop(61)
    dat = dat.drop(0)
    dat = dat.rename(columns= {2008.0: 2008, 2009.0: 2009, 2010.0: 2010, 2011.0: 2011, 2012.0: 2012, 2013.0: 2013, 2014.0: 2014,
                           2015.0: 2015, 2016.0: 2016, 2017.0: 2017, 2018.0: 2018, 2019.0: 2019, 2020.0: 2020})
    dat = dat[['Region/state of residence', 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]]
    # dat = pd.DataFrame(dat).set_index('Region/state of residence')
    if data.equals(df2):
        dat.to_csv(f'Data\{name2}.csv', encoding='utf-8', index=False)
    elif data.equals(df3):
        dat.to_csv(f'Data\{name3}.csv', encoding='utf-8', index=False)
    elif data.equals(df4):
        dat.to_csv(f'Data\{name4}.csv', encoding='utf-8', index=False)
    elif data.equals(df5):
        dat.to_csv(f'Data\{name5}.csv', encoding='utf-8', index=False)
    elif data.equals(df7):
        dat.to_csv(f'Data\{name7}.csv', encoding='utf-8', index=False)
    elif data.equals(df8):
        dat.to_csv(f'Data\{name8}.csv', encoding='utf-8', index=False)
    elif data.equals(df14):
        dat.to_csv(f'Data\{name14}.csv', encoding='utf-8', index=False)
    return dat

In [ ]:
clean(df2), clean(df3), clean(df4), clean(df5), clean(df7), clean(df8), clean(df14)